//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Formula.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FormulaCS.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class FormulaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, STRING=17, 
		BOOLEAN=18, NUMBER=19, NAME=20, S=21, INVALID=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "STRING", 
		"BOOLEAN", "NUMBER", "NAME", "S", "INVALID", "DIGIT", "TRUE", "FALSE", 
		"FLOAT", "E"
	};


	public FormulaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public FormulaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'+'", "'-'", "'%'", "'^'", "'*'", "'/'", "'&'", "'='", "'<>'", 
		"'<'", "'>'", "'<='", "'>='", "'('", "')'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, "STRING", "BOOLEAN", "NUMBER", "NAME", "S", 
		"INVALID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Formula.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static FormulaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\xAE', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '_', 
		'\n', '\x12', '\f', '\x12', '\xE', '\x12', '\x62', '\v', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', 'h', 
		'\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x6', '\x14', 'l', '\n', 
		'\x14', '\r', '\x14', '\xE', '\x14', 'm', '\x5', '\x14', 'p', '\n', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\a', '\x15', 't', '\n', '\x15', '\f', '\x15', 
		'\xE', '\x15', 'w', '\v', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x6', '\x1B', '\x8D', '\n', '\x1B', 
		'\r', '\x1B', '\xE', '\x1B', '\x8E', '\x3', '\x1B', '\x3', '\x1B', '\x6', 
		'\x1B', '\x93', '\n', '\x1B', '\r', '\x1B', '\xE', '\x1B', '\x94', '\x3', 
		'\x1B', '\x5', '\x1B', '\x98', '\n', '\x1B', '\x3', '\x1B', '\x6', '\x1B', 
		'\x9B', '\n', '\x1B', '\r', '\x1B', '\xE', '\x1B', '\x9C', '\x3', '\x1B', 
		'\x3', '\x1B', '\x5', '\x1B', '\xA1', '\n', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x5', '\x1C', '\xA5', '\n', '\x1C', '\x3', '\x1C', '\x5', '\x1C', 
		'\xA8', '\n', '\x1C', '\x3', '\x1C', '\x6', '\x1C', '\xAB', '\n', '\x1C', 
		'\r', '\x1C', '\xE', '\x1C', '\xAC', '\x2', '\x2', '\x1D', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x2', '\x31', '\x2', '\x33', '\x2', '\x35', '\x2', '\x37', '\x2', 
		'\x3', '\x2', '\xF', '\x3', '\x2', '$', '$', '\x6', '\x2', '\x43', '\\', 
		'^', '^', '\x61', '\x61', '\x63', '|', '\b', '\x2', '\x30', '\x30', '\x32', 
		';', '\x43', '\\', '^', '^', '\x61', '\x61', '\x63', '|', '\x5', '\x2', 
		'\v', '\f', '\xE', '\xF', '\"', '\"', '\x3', '\x2', '\x32', ';', '\x4', 
		'\x2', 'V', 'V', 'v', 'v', '\x4', '\x2', 'T', 'T', 't', 't', '\x4', '\x2', 
		'W', 'W', 'w', 'w', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', 'H', 
		'H', 'h', 'h', '\x4', '\x2', '\x43', '\x43', '\x63', '\x63', '\x4', '\x2', 
		'N', 'N', 'n', 'n', '\x4', '\x2', 'U', 'U', 'u', 'u', '\x2', '\xB5', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'-', '\x3', '\x2', '\x2', '\x2', '\x3', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\x5', ';', '\x3', '\x2', '\x2', '\x2', '\a', '=', '\x3', '\x2', '\x2', 
		'\x2', '\t', '?', '\x3', '\x2', '\x2', '\x2', '\v', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\r', '\x43', '\x3', '\x2', '\x2', '\x2', '\xF', '\x45', 
		'\x3', '\x2', '\x2', '\x2', '\x11', 'G', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'I', '\x3', '\x2', '\x2', '\x2', '\x15', 'L', '\x3', '\x2', '\x2', '\x2', 
		'\x17', 'N', '\x3', '\x2', '\x2', '\x2', '\x19', 'P', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', 'S', '\x3', '\x2', '\x2', '\x2', '\x1D', 'V', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', 'X', '\x3', '\x2', '\x2', '\x2', '!', 'Z', '\x3', 
		'\x2', '\x2', '\x2', '#', '\\', '\x3', '\x2', '\x2', '\x2', '%', 'g', 
		'\x3', '\x2', '\x2', '\x2', '\'', 'o', '\x3', '\x2', '\x2', '\x2', ')', 
		'q', '\x3', '\x2', '\x2', '\x2', '+', 'x', '\x3', '\x2', '\x2', '\x2', 
		'-', '|', '\x3', '\x2', '\x2', '\x2', '/', '~', '\x3', '\x2', '\x2', '\x2', 
		'\x31', '\x80', '\x3', '\x2', '\x2', '\x2', '\x33', '\x85', '\x3', '\x2', 
		'\x2', '\x2', '\x35', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x37', '\xA2', 
		'\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', '-', '\x2', '\x2', ':', 
		'\x4', '\x3', '\x2', '\x2', '\x2', ';', '<', '\a', '/', '\x2', '\x2', 
		'<', '\x6', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '\'', '\x2', '\x2', 
		'>', '\b', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '`', '\x2', '\x2', 
		'@', '\n', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', ',', '\x2', 
		'\x2', '\x42', '\f', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', 
		'\x31', '\x2', '\x2', '\x44', '\xE', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\a', '(', '\x2', '\x2', '\x46', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'G', 'H', '\a', '?', '\x2', '\x2', 'H', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'J', '\a', '>', '\x2', '\x2', 'J', 'K', '\a', '@', '\x2', 
		'\x2', 'K', '\x14', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', '>', '\x2', 
		'\x2', 'M', '\x16', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\a', '@', '\x2', 
		'\x2', 'O', '\x18', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\a', '>', '\x2', 
		'\x2', 'Q', 'R', '\a', '?', '\x2', '\x2', 'R', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', '@', '\x2', '\x2', 'T', 'U', '\a', '?', '\x2', 
		'\x2', 'U', '\x1C', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\a', '*', '\x2', 
		'\x2', 'W', '\x1E', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\a', '+', '\x2', 
		'\x2', 'Y', ' ', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '.', '\x2', 
		'\x2', '[', '\"', '\x3', '\x2', '\x2', '\x2', '\\', '`', '\a', '$', '\x2', 
		'\x2', ']', '_', '\n', '\x2', '\x2', '\x2', '^', ']', '\x3', '\x2', '\x2', 
		'\x2', '_', '\x62', '\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x64', '\a', '$', '\x2', '\x2', '\x64', '$', '\x3', '\x2', '\x2', '\x2', 
		'\x65', 'h', '\x5', '\x31', '\x19', '\x2', '\x66', 'h', '\x5', '\x33', 
		'\x1A', '\x2', 'g', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', '\x66', '\x3', 
		'\x2', '\x2', '\x2', 'h', '&', '\x3', '\x2', '\x2', '\x2', 'i', 'p', '\x5', 
		'\x35', '\x1B', '\x2', 'j', 'l', '\x5', '/', '\x18', '\x2', 'k', 'j', 
		'\x3', '\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', 
		'k', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', '\x2', '\x2', 
		'n', 'p', '\x3', '\x2', '\x2', '\x2', 'o', 'i', '\x3', '\x2', '\x2', '\x2', 
		'o', 'k', '\x3', '\x2', '\x2', '\x2', 'p', '(', '\x3', '\x2', '\x2', '\x2', 
		'q', 'u', '\t', '\x3', '\x2', '\x2', 'r', 't', '\t', '\x4', '\x2', '\x2', 
		's', 'r', '\x3', '\x2', '\x2', '\x2', 't', 'w', '\x3', '\x2', '\x2', '\x2', 
		'u', 's', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\x3', '\x2', '\x2', '\x2', 
		'v', '*', '\x3', '\x2', '\x2', '\x2', 'w', 'u', '\x3', '\x2', '\x2', '\x2', 
		'x', 'y', '\t', '\x5', '\x2', '\x2', 'y', 'z', '\x3', '\x2', '\x2', '\x2', 
		'z', '{', '\b', '\x16', '\x2', '\x2', '{', ',', '\x3', '\x2', '\x2', '\x2', 
		'|', '}', '\v', '\x2', '\x2', '\x2', '}', '.', '\x3', '\x2', '\x2', '\x2', 
		'~', '\x7F', '\t', '\x6', '\x2', '\x2', '\x7F', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '\x81', '\t', '\a', '\x2', '\x2', '\x81', '\x82', 
		'\t', '\b', '\x2', '\x2', '\x82', '\x83', '\t', '\t', '\x2', '\x2', '\x83', 
		'\x84', '\t', '\n', '\x2', '\x2', '\x84', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x86', '\t', '\v', '\x2', '\x2', '\x86', '\x87', '\t', 
		'\f', '\x2', '\x2', '\x87', '\x88', '\t', '\r', '\x2', '\x2', '\x88', 
		'\x89', '\t', '\xE', '\x2', '\x2', '\x89', '\x8A', '\t', '\n', '\x2', 
		'\x2', '\x8A', '\x34', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8D', '\x5', 
		'/', '\x18', '\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x92', '\a', '\x30', '\x2', '\x2', '\x91', 
		'\x93', '\x5', '/', '\x18', '\x2', '\x92', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x97', '\x3', '\x2', '\x2', '\x2', '\x96', '\x98', '\x5', '\x37', '\x1C', 
		'\x2', '\x97', '\x96', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\x98', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9B', '\x5', '/', '\x18', '\x2', '\x9A', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9D', 
		'\x9E', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\x5', '\x37', '\x1C', 
		'\x2', '\x9F', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\x9A', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA7', '\t', '\n', '\x2', 
		'\x2', '\xA3', '\xA5', '\a', '-', '\x2', '\x2', '\xA4', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA8', '\a', '/', '\x2', 
		'\x2', '\xA7', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xA9', 
		'\xAB', '\x5', '/', '\x18', '\x2', '\xAA', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\x10', '\x2', '`', 'g', 'm', 'o', 
		'u', '\x8E', '\x94', '\x97', '\x9C', '\xA0', '\xA4', '\xA7', '\xAC', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace FormulaCS.Parser
